In [23]:
from pyspark.sql import SparkSession
import mysql.connector

In [24]:
# Spark 세션 시작
spark = SparkSession.builder \
    .appName("CSV to MariaDB") \
    .getOrCreate()

In [25]:
connection = mysql.connector.connect(
    host="13.124.90.34",
    user="root",
    password="enqnrhkwk108",
    database="S11P21D108",
    charset="utf8mb4",  # 문자셋 설정
    collation="utf8mb4_general_ci",  # collation 설정
    autocommit=False,  # Auto-commit을 끄고 트랜잭션 처리
    connection_timeout=28800,  # 타임아웃 증가
)

In [26]:
# CSV 파일 읽기
area_df = spark.read.option("encoding", "cp949").csv("hdfs://master:9000/input/서울시_상권분석서비스(추정매출-상권).csv", header=True, inferSchema=True)

In [27]:
# CSV 파일 읽기
dong_df = spark.read.option("encoding", "cp949").csv("hdfs://master:9000/input/서울시_상권분석서비스(추정매출-행정동).csv", header=True, inferSchema=True)

In [28]:
# CSV 파일 읽기
gu_df = spark.read.option("encoding", "cp949").csv("hdfs://master:9000/input/서울시_상권분석서비스(추정매출-자치구).csv", header=True, inferSchema=True)

In [29]:
# 필요한 컬럼 선택
area_df = area_df.select('기준_년분기_코드', '상권_코드', '상권_코드_명', '서비스_업종_코드',
                     '서비스_업종_코드_명', '당월_매출_금액', '주중_매출_금액', '주말_매출_금액',
                     '월요일_매출_금액', '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', 
                     '금요일_매출_금액', '토요일_매출_금액', '일요일_매출_금액', '시간대_00~06_매출_금액', 
                     '시간대_06~11_매출_금액', '시간대_11~14_매출_금액', '시간대_14~17_매출_금액', 
                     '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액', '여성_매출_금액', 
                     '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액', 
                     '연령대_50_매출_금액', '연령대_60_이상_매출_금액')

# 기준_년분기_코드가 20241인 데이터 필터링
area_2024 = area_df.filter(area_df['기준_년분기_코드'] == 20241)

# 결과 확인
area_2024.show()

+----------------+---------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
|기준_년분기_코드|상권_코드|  상권_코드_명|서비스_업종_코드|서비스_업종_코드_명|당월_매출_금액|주중_매출_금액|주말_매출_금액|월요일_매출_금액|화요일_매출_금액|수요일_매출_금액|목요일_매출_금액|금요일_매출_금액|토요일_매출_금액|일요일_매출_금액|시간대_00~06_매출_금액|시간대_06~11_매출_금액|시간대_11~14_매출_금액|시간대_14~17_매출_금액|시간대_17~21_매출_금액|시간대_21~24_매출_금액|남성_매출_금액|여성_매출_금액|연령대_10_매출_금액|연령대_20_매출_금액|연령대_30_매출_금액|연령대_40_매출_금액|연령대_50_매출_금액|연령대_60_이상_매출_금액|
+----------------+---------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
|           20241|  3110001|   이북5도청사|        CS100001|         한식음식점|     459850342|     243372198|     216478144|        34495045|        35651521|        61236387|        53763816|        58225429|       104282956|       112195188|                     0|               8466267|             153835186|              96008321|             192560387|               8980181|     251885379|     141835143|             145032|           12532338|           39393251|           63781120|          106416637|               171452142|
|           20241|  3110001|   이북5도청사|        CS100008|         분식전문점|     124263123|      68892376|      55370747|        13681626|        12403281|        14969777|        13563575|        14274117|        31300945|        24069802|                872346|              48452085|              50968658|              14258970|               9711064|                     0|      55961722|      58673112|             177450|            4700828|           11386337|           26652317|           40097951|                31619952|
|           20241|  3110001|   이북5도청사|        CS100009|      호프-간이주점|       9913875|       6445108|       3468767|               0|          354320|           81755|         2861434|         3147599|         2225249|         1243518|               1760462|                     0|                     0|                724953|               3111783|               4316677|       7140825|        876226|                  0|                  0|                  0|            1760463|            2792754|                 3463834|
|           20241|  3110002|  독립문역 1번|        CS100001|         한식음식점|     458693088|     328079516|     130613572|        64504879|        69267665|        66623225|        62145378|        65538369|        82087799|        48525773|               4503859|               9126827|             213927151|              86932938|             120410508|              23791805|     268526238|     154599258|             374862|           17616190|           46757494|           73685269|          117503777|               167187902|
|           20241|  3110002|  독립문역 1번|        CS200001|       일반교습학원|      30028494|      30028494|             0|         1858630|               0|         9235068|        17366577|         1568219|               0|               0|                     0|                     0|               6214795|               2032877|              20212603|               1568219|      22071233|       7957261|                  0|                  0|                  0|           20444931|            9583563|                       0|
|           20241|  3110002|  독립문역 1번|        CS300002|             편의점|    1741773594|    1205014669|     536758925|       224625565|       225933678|       245438429|       239756367|       269260630|       263442768|       273316157|             123922502|             321650486|             288931374|             278223814|             485124848|             243920570|    1102118896|     600898824|           16845284|          220009763|          292914488|          370225097|          479910541|               323112547|
|           20241|  3110002|  독립문역 1번|        CS300018|             의약품|    3791674246|    3679384786|     112289460|       735218441|       736707095|       707498900|       754702797|       745257553|       112289460|               0|                     0|            1029866720|            1093327521|            1359868681|             308611324|                     0|    1758443896|    2033230350|             427449|           58058282|          143364185|          496654966|          922891259|              2170278105|
|           20241|  3110002|  독립문역 1번|        CS300022|             화장품|     156383595|     138755496|      17628099|        25750105|        24864898|        31879633|        24905963|        31354897|        16107124|         1520975|                     0|              28107616|              44865718|              48237718|              32891081|               2281462|      74357420|      82026175|                  0|                  0|                  0|           13954945|           34561113|               107867537|
|           20241|  3110003|세검정초등학교|        CS100001|         한식음식점|     207608854|     165211643|      42397211|        33583538|        34000670|        34165153|        25034425|        38427857|        38882925|         3514286|                692144|                633813|             100189325|              27519312|              66849136|              11725124|     105118324|      76239128|             227147|            2908863|           16085976|           34618041|           49702343|                77815081|
|           20241|  3110003|세검정초등학교|        CS100008|         분식전문점|      34652870|      29312083|       5340787|         6461105|         6478889|         6028391|         5577891|         4765807|         5340787|               0|                     0|                     0|              15589643|               6206218|              12857009|                     0|      17732139|      15053530|            1401344|            1778892|            3993347|           11410480|           10979799|                 3221808|
|           20241|  3110003|세검정초등학교|        CS100009|      호프-간이주점|     167029729|     133650245|      33379484|         9118453|        46771991|        48574514|         9951912|        19233375|        19552922|        13826562|              59073037|                     0|                159515|                834831|              22399866|              84562480|     122637917|      36389500|            1366246|           15484298|           13970844|           13630001|          101712558|                12863471|
|           20241|  3110003|세검정초등학교|        CS100010|          커피-음료|      24000340|      17871782|       6128558|         4213119|         4006074|         3172581|         4478564|         2001444|         2528083|         3600475|                     0|               1656367|              10702683|               9962626|               1678664|                     0|      10776357|      11755549|             140343|            4454929|            8185982|            3843038|            4548821|                 1358794|
|           20241|  3110003|세검정초등학교|        CS200001|       일반교습학원|      20841789|      18353648|       2488141|         4217353|         3770638|         4265386|         2978085|         3122186|               0|         2488141|                     0|               3439207|               5946563|               6340438|               5115581|                     0|       5427800|      14261182|                  0|                  0|             720504|           10754728|            8213750|                       0|
|           20241|  3110003|세검정초등학교|        CS200003|           예술학원|      67204717|      67204717|             0|         9782416|        17122618|        18295561|        12206198|         9797924|               0|               0|                     0|                     0|               2978812|              41392165|              22833740|                     0|      23884100|      43320617|                  0|                  0|            6116834|           40021433|           21066450|                       0|
|           20241|  3110003|세검정초등학교|        CS200028|             미용실|      70378437|      60774733|       9603704|         5000086|        10351156|         2400058|         7084000|        35939433|         9102068|          501636|                     0|               3497497|              18782626|              15268179|              31357917|               1472218|      16697890|      53571917|             167212|             143392|            5018246|           12958078|           11901741|                40081138|
|           20241|  3110003|세검정초등학교|        CS200031|             세탁소|       2745327|       2745327|             0|          315421|          560748|               0|               0|         1869158|               0|               0|                     0|               1518692|                     0|                514018|                712617|                     0|        315421|       2429906|                  0|                  0|             151869|             151869|            1869159|                  572430|
|           20241|  3110003|세검정초등학교|        CS300011|           일반의류|     274167178|     267412367|       6754811|               0|        22434368|        77667625|         8850374|       158460000|         6754811|               0|                     0|                     0|              18923437|              58475573|             196768168|                     0|             0|     274167178|                  0|                  0|                  0|                  0|           29637867|               244529311|
|           20241|  3110004|  대신고등학교|        CS100001|         한식음식점|     377334991|     223465737|     153869254|        45488640|        27639354|        40203912|        43994751|        66139080|        74139491|        79729763|                     0|              13788307|              93276412|              82190103|             165611513|              22468656|     203884101|     105347727|              47595|            9547087|           34137555|           73105116|           91261944|               101132528|
|           20241|  3110005|        세검정|        CS100001|         한식음식점|     289485898|     188575308|     100910590|        14187040|        46797641|        33232241|        50042949|        44315437|        61796056|        39114534|               2830915|               2728267|             107263251|              45357857|             106903252|              24402356|     126820097|     111201599|             740393|           16270402|           37025791|           34094990|           60340293|                89549827|
|           20241|  3110005|        세검정|        CS200001|       일반교습학원|     411000000|     389822095|      21177905|       107913894|        57557024|        56479430|       117868612|        50003135|        15378415|         5799490|               8678626|              29715307|              28401859|             103209850|             212267505|              28726853|     216385108|     194614892|                  0|                  0|            8883412|          226571803|          175544785|                       0|
+----------------+---------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
only showing top 20 rows

In [30]:
# 필요한 컬럼 선택
dong_df = dong_df.select('기준_년분기_코드', '행정동_코드','행정동_코드_명', '서비스_업종_코드',
                     '서비스_업종_코드_명', '당월_매출_금액', '주중_매출_금액', '주말_매출_금액',
                     '월요일_매출_금액', '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', 
                     '금요일_매출_금액', '토요일_매출_금액', '일요일_매출_금액', '시간대_00~06_매출_금액', 
                     '시간대_06~11_매출_금액', '시간대_11~14_매출_금액', '시간대_14~17_매출_금액', 
                     '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액', '여성_매출_금액', 
                     '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액', 
                     '연령대_50_매출_금액', '연령대_60_이상_매출_금액')

# 기준_년분기_코드가 20241인 데이터 필터링
dong_2024 = dong_df.filter(dong_df['기준_년분기_코드'] == 20241)

# 결과 확인
dong_2024.show()

+----------------+-----------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
|기준_년분기_코드|행정동_코드|행정동_코드_명|서비스_업종_코드|서비스_업종_코드_명|당월_매출_금액|주중_매출_금액|주말_매출_금액|월요일_매출_금액|화요일_매출_금액|수요일_매출_금액|목요일_매출_금액|금요일_매출_금액|토요일_매출_금액|일요일_매출_금액|시간대_00~06_매출_금액|시간대_06~11_매출_금액|시간대_11~14_매출_금액|시간대_14~17_매출_금액|시간대_17~21_매출_금액|시간대_21~24_매출_금액|남성_매출_금액|여성_매출_금액|연령대_10_매출_금액|연령대_20_매출_금액|연령대_30_매출_금액|연령대_40_매출_금액|연령대_50_매출_금액|연령대_60_이상_매출_금액|
+----------------+-----------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
|           20241|   11110515|    청운효자동|        CS100001|         한식음식점|    3818701234|    2713940429|    1104760805|       453547926|       504938402|       531476590|       593180731|       630796780|       708007662|       396753143|              15158965|              56148213|            1356917391|             603631197|            1502686345|             284159123|    1588478454|    1469764086|           10369430|          517093516|          784868144|          566636067|          613882688|               565392707|
|           20241|   11110515|    청운효자동|        CS100003|         일식음식점|     393947601|     258578001|     135369600|        24441277|        39951969|        67770360|        59224702|        67189693|        81739025|        53630575|               4007287|                     0|             190442284|              48341073|             120476967|              30679990|     131196185|     191277895|            4093768|          120000964|           95720806|           44933135|           42397582|                15327824|
|           20241|   11110515|    청운효자동|        CS100004|         양식음식점|    1979610607|    1148347500|     831263107|       102273034|       224905970|       230087455|       284520482|       306560559|       513606025|       317657082|              27505976|              20382961|             513522808|             375063877|             810369986|             232764999|     707405691|    1010037500|            4936133|          411604203|          629870611|          244970929|          269013781|               157047537|
|           20241|   11110515|    청운효자동|        CS100005|             제과점|     829881348|     481893005|     347988343|        80458144|        84190592|       110442559|        96690449|       110111261|       214157019|       133831324|                     0|              74981868|             217666468|             329515664|             192324765|              15392583|     292729277|     496929127|            2180231|          160945723|          224782655|          158459078|          151508974|                91781747|
|           20241|   11110515|    청운효자동|        CS100008|         분식전문점|    1088859348|     784377305|     304482043|        58136883|       165698643|       192063210|       172024535|       196454034|       197458523|       107023520|               2957997|              45254986|             330253824|             241671874|             361753737|             106966930|     312280901|     591699411|            5433031|          181068912|          403218401|          157362676|           90313654|                66583642|
|           20241|   11110515|    청운효자동|        CS100009|      호프-간이주점|     133652524|      78313170|      55339354|        11341843|        11616180|        16815179|        18070490|        20469478|        33030196|        22309158|              16879271|                     0|                     0|               6929690|              41741296|              68102267|      57839520|      62880608|              90302|           34020905|           52123757|            9295378|            9793242|                15396545|
|           20241|   11110515|    청운효자동|        CS100010|          커피-음료|    3934521549|    2410792850|    1523728699|       402554473|       403525223|       636083385|       422365421|       546264348|       830999606|       692729093|               2204276|             238724871|            1094287217|            1427806957|             920296328|             251201900|    1168656657|    2473194400|           11563947|          930272866|         1075107920|          675091874|          500125159|               449689290|
|           20241|   11110515|    청운효자동|        CS200001|       일반교습학원|     461315593|     364322130|      96993463|        59518717|        44017433|       183250088|        51341919|        26193973|        72745097|        24248366|               1066946|              47714929|              79358290|             114654991|             192067674|              26452763|     249061599|     212253994|                  0|                  0|                  0|          182956043|          278359550|                       0|
|           20241|   11110515|    청운효자동|        CS200002|         외국어학원|       4370491|       2431967|       1938524|         2431967|               0|               0|               0|               0|         1938524|               0|                     0|               2431967|                     0|                     0|                     0|               1938524|             0|       4370491|                  0|                  0|                  0|            4370491|                  0|                       0|
|           20241|   11110515|    청운효자동|        CS200003|           예술학원|     151301773|     147237744|       4064029|        21034420|        37335164|        66479746|         9691146|        12697268|         4064029|               0|                     0|               4064029|                     0|              48358332|              90751354|               8128058|      70263932|      81037841|                  0|                  0|           28702683|          119529646|            3069444|                       0|
|           20241|   11110515|    청운효자동|        CS200005|        스포츠 강습|      10200000|      10200000|             0|         6800000|               0|         3400000|               0|               0|               0|               0|                     0|                     0|                     0|                     0|              10200000|                     0|             0|      10200000|                  0|                  0|                  0|           10200000|                  0|                       0|
|           20241|   11110515|    청운효자동|        CS200006|           일반의원|     536151220|     462243852|      73907368|        91063361|       109988782|        95029794|        88554292|        77607623|        73907368|               0|                     0|             135114798|             168875579|             149250599|              82910244|                     0|     226803372|     309347848|            5778684|           40315584|           85182388|          145096583|          100719104|               159058877|
|           20241|   11110515|    청운효자동|        CS200026|         자동차미용|     209786440|     185527765|      24258675|        39161792|        37658519|        43213916|        31313904|        34179634|        24258675|               0|                     0|              35174137|              68010942|              76785562|              29815799|                     0|      95415955|      55742234|                  0|            9245315|           17967736|           24535230|           69084361|                30325544|
|           20241|   11110515|    청운효자동|        CS200028|             미용실|     174043977|     125650892|      48393085|        16528085|        25888592|        28350595|        23553002|        31330618|        35907693|        12485392|                     0|               5519662|              44954661|              65364097|              55471154|               2734403|      68593699|     104849857|            2085839|            7913407|           18699922|           36852852|           58798796|                49092739|
|           20241|   11110515|    청운효자동|        CS200030|         피부관리실|      11863338|       2849362|       9013976|          536170|          612766|          434043|          449362|          817021|         1307235|         7706741|                     0|                     0|                908937|               1511489|               2170213|               7272699|        142979|      11720359|                  0|            1302127|            3145533|             142979|                  0|                 7272699|
|           20241|   11110515|    청운효자동|        CS200031|             세탁소|      44607989|      35555042|       9052947|         7003646|         8025390|         7526941|         6162207|         6836858|         9052947|               0|                     0|               7913928|              12048762|              17156848|               7488451|                     0|      22618427|      20510143|              41893|             670790|            6880556|           10379001|           10847929|                14308400|
|           20241|   11110515|    청운효자동|        CS300001|           슈퍼마켓|    1830015292|    1365063099|     464952193|       267985459|       258101922|       270673382|       278133458|       290168878|       283219569|       181732624|               6328886|             222509685|             369072504|             443861877|             624949352|             163292988|     800619648|     864296567|           13023460|           99528880|          207088275|          328318083|          430024295|               586933222|
|           20241|   11110515|    청운효자동|        CS300002|             편의점|     881795942|     614182361|     267613581|       119926821|       117368290|       119497896|       118645374|       138743980|       141827760|       125785821|              66970215|             112444454|             130009959|             130180497|             262243504|             179947313|     515110205|     316080399|           12383423|          114831753|          218334011|          202671343|          171571311|               111398767|
|           20241|   11110515|    청운효자동|        CS300006|           미곡판매|      16796575|      16796575|             0|         4881763|               0|         7943208|               0|         3971604|               0|               0|                     0|                     0|              16796575|                     0|                     0|                     0|       3971604|      12824971|                  0|                  0|                  0|                  0|                  0|                16796575|
|           20241|   11110515|    청운효자동|        CS300007|           육류판매|     343055387|     261374546|      81680841|        33599651|        80595855|        81898522|        22024396|        43256122|        52759529|        28921312|                     0|              75149845|              81487659|              98523673|              87894210|                     0|      68167070|     167152516|                  0|            7210882|           12990815|           79176849|           70713592|                65227446|
+----------------+-----------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
only showing top 20 rows

In [31]:
# 필요한 컬럼 선택
gu_df = gu_df.select('기준_년분기_코드','자치구_코드','자치구_코드_명', '서비스_업종_코드',
                     '서비스_업종_코드_명', '당월_매출_금액', '주중_매출_금액', '주말_매출_금액',
                     '월요일_매출_금액', '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', 
                     '금요일_매출_금액', '토요일_매출_금액', '일요일_매출_금액', '시간대_00~06_매출_금액', 
                     '시간대_06~11_매출_금액', '시간대_11~14_매출_금액', '시간대_14~17_매출_금액', 
                     '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액', '여성_매출_금액', 
                     '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액', '연령대_40_매출_금액', 
                     '연령대_50_매출_금액', '연령대_60_이상_매출_금액')

# 기준_년분기_코드가 20241인 데이터 필터링
gu_2024 = gu_df.filter(gu_df['기준_년분기_코드'] == 20241)

# 결과 확인
gu_2024.show()

+----------------+-----------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
|기준_년분기_코드|자치구_코드|자치구_코드_명|서비스_업종_코드|서비스_업종_코드_명|당월_매출_금액|주중_매출_금액|주말_매출_금액|월요일_매출_금액|화요일_매출_금액|수요일_매출_금액|목요일_매출_금액|금요일_매출_금액|토요일_매출_금액|일요일_매출_금액|시간대_00~06_매출_금액|시간대_06~11_매출_금액|시간대_11~14_매출_금액|시간대_14~17_매출_금액|시간대_17~21_매출_금액|시간대_21~24_매출_금액|남성_매출_금액|여성_매출_금액|연령대_10_매출_금액|연령대_20_매출_금액|연령대_30_매출_금액|연령대_40_매출_금액|연령대_50_매출_금액|연령대_60_이상_매출_금액|
+----------------+-----------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
|           20241|      11650|        서초구|        CS200036|             고시원|     210886250|     170386250|      40500000|        34714286|        48886250|        46285714|               0|        40500000|        40500000|               0|                     0|              40500000|              46285714|              75214286|                     0|              48886250|     127285714|      83600536|                  0|                  0|                  0|                  0|          210886250|                       0|
|           20241|      11650|        서초구|        CS300014|               신발|     441732441|     358142607|      83589834|        58517568|       105942612|        73233259|        54927302|        65521866|        51173856|        32415978|                     0|              21433388|              79262386|             246900097|              94136570|                     0|     149149173|     279913947|             357226|              24807|           19669776|           37742689|           61654885|               309613738|
|           20241|      11650|        서초구|        CS300015|               가방|     465036043|     463571031|       1465012|               0|         3387841|               0|       460183190|               0|         1465012|               0|                     0|                     0|                549380|             413355197|              51131466|                     0|             0|     465036043|                  0|                  0|                  0|                  0|             915633|               464120410|
|           20241|      11560|      영등포구|        CS200036|             고시원|     452441519|     309090996|     143350523|        55810567|        51131817|        66086693|        22500530|       113561389|        64629553|        78720970|              75913976|               5568493|              49804403|              67066327|             172700029|              81388291|     297173445|     149803665|            4231152|           47849082|          193464875|           82590192|           39087612|                79754197|
|           20241|      11740|        강동구|        CS300015|               가방|      17266141|      10957903|       6308238|               0|         6357907|          844856|         2473624|         1281516|         5215472|         1092766|                     0|                     0|               4520522|               9775283|               2970336|                     0|       1043541|      16023915|                  0|                  0|                  0|             397369|            4172824|                12497263|
|           20241|      11110|        종로구|        CS100001|         한식음식점|  225384924971|  167895664015|   57489260956|     28753197051|     31881210430|     34801751370|     35682572426|     36776932738|     35062257862|     22427003094|            5254988440|            2671244707|           72242976079|           26486193274|           89191977809|           29537544662|  104568331111|   69822140643|          555916159|        25267909711|        40931767833|        33807959484|        37039230378|             36787688183|
|           20241|      11110|        종로구|        CS200005|        스포츠 강습|    1957381525|    1816772105|     140609420|       348142481|       415407225|       411324210|       366022278|       275875911|       101962444|        38646976|               7021581|             171378084|             424787926|             395138413|             778970591|             180084930|     407518884|    1489424940|                  0|          312336094|          486458101|          775637461|          275532833|                46979335|
|           20241|      11110|        종로구|        CS200031|             세탁소|     458084235|     323722945|     134361290|        57247740|        51504301|        65117237|        46860933|       102992734|       103149108|        31212182|               8745527|              63394105|             128274835|             110080210|             112005790|              35583768|     173241914|     213690773|             461182|           81790699|           75486178|           58793461|          105927407|                64473759|
|           20241|      11110|        종로구|        CS200036|             고시원|     155505453|     141249279|      14256174|        31671855|         4095697|        54076543|         9320335|        42084849|        14256174|               0|                     0|                551344|              60567333|              64059836|              30326940|                     0|      33093776|     120757646|                  0|           40805240|            1436153|           70364877|            1823711|                39421440|
|           20241|      11110|        종로구|        CS300018|             의약품|   62332377622|   52624920472|    9707457150|      9867762820|     10839867234|     10616816948|     11025495531|     10274977939|      7706284393|      2001172757|                511645|           11466212801|           20291178938|           21510794390|            8971380520|              92299328|   33881816721|   28308426700|           31052120|         3153593977|         9054682484|        10855472462|        13549008548|             25546433824|
|           20241|      11110|        종로구|        CS300020|               서적|    7247953751|    6603680154|     644273597|      1761284315|      1011152120|       692967025|      1874096352|      1264180342|       369618581|       274655016|                 87784|            1552744397|            3555545294|            1208832347|             906454067|              24289862|    1127648917|    5308422161|           13885115|         2132701871|          382980713|          628026622|          416895984|              2861580771|
|           20241|      11110|        종로구|        CS300028|               화초|    2507072718|    2194903779|     312168939|       269448274|       345803808|       624695502|       568532299|       386423896|       194529744|       117639195|                     0|             333891115|             718005069|             903189691|             532205215|              19781628|     929388159|     858050120|            6249278|          219222949|          614128542|          393463248|          373039591|               180172599|
|           20241|      11140|          중구|        CS100006|       패스트푸드점|    6369782864|    4989886903|    1379895961|       839986171|       989095470|      1039121440|      1054178656|      1067505166|       745160956|       634735005|             223835923|             574636721|            2449098724|             962019942|            1875317414|             284874140|    2738014437|    2471403952|           39552685|         1099469809|         1766608867|         1172811590|          754370362|               376605072|
|           20241|      11140|          중구|        CS300007|           육류판매|   30413385716|   26632220831|    3781164885|      3169200309|      4028589576|      7329206459|      4274855332|      7830369155|      3082096280|       699068605|              12428341|           10803276242|            5125679477|           10335276826|            3933495445|             203229385|    7293995686|   21356957404|             417473|          250708918|         1546375454|         2652469106|         4098083091|             20102899045|
|           20241|      11170|        용산구|        CS100001|         한식음식점|  125415881355|   91993643558|   33422237797|     15557411424|     17536717810|     18419404051|     20052629621|     20427480652|     19409604396|     14012633401|            7165269521|            2374711189|           31215224104|            9816169515|           50697282927|           24147224099|   56462720735|   38000782365|          214857320|        17970892867|        30537909509|        17173089776|        16426632839|             12140120817|
|           20241|      11170|        용산구|        CS100002|         중식음식점|    7786721374|    5723869648|    2062851726|       733658918|      1114015691|      1212556787|      1259693429|      1403944823|      1205244776|       857606950|             151287429|              16057930|            2764816685|             648210871|            3153719827|            1052628632|    3637197171|    2437577805|           25677614|         1150591873|         1796583859|         1198733009|         1129405624|               773782999|
|           20241|      11170|        용산구|        CS200005|        스포츠 강습|    1090073870|    1034611822|      55462048|       218767201|       301150593|       162921219|       233196927|       118575882|        55462048|               0|                     0|             116807043|             205469092|             309565781|             340000159|             118231795|     387752337|     647657766|              76471|          112991118|          294424793|          356287985|          142251230|               129378511|
|           20241|      11170|        용산구|        CS200024|         스포츠클럽|    3316152932|    3143187506|     172965426|       834887043|       798228191|       555069566|       414184874|       540817832|       117256841|        55708585|              28812863|             547024046|             617877244|             683669326|            1257172204|             181597249|    1385904867|    1211048013|                  0|          292778073|          909315181|          592360074|          482264365|               320235184|
|           20241|      11170|        용산구|        CS200033|       부동산중개업|      15400000|      15400000|             0|               0|               0|               0|               0|        15400000|               0|               0|                     0|                     0|              15400000|                     0|                     0|                     0|             0|      15400000|                  0|                  0|                  0|                  0|           15400000|                       0|
|           20241|      11170|        용산구|        CS300022|             화장품|   11357026776|    8363880560|    2993146216|      1547690312|      1502954112|      1704545543|      1628531876|      1980158717|      1675618243|      1317527973|             117868145|             555283356|            2710675798|            3220498709|            4031799743|             720901025|    3448081451|    7792807435|           96270509|         2835037566|         2970010376|         1580393906|         1691551579|              2067624947|
+----------------+-----------+--------------+----------------+-------------------+--------------+--------------+--------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+--------------+--------------+-------------------+-------------------+-------------------+-------------------+-------------------+------------------------+
only showing top 20 rows

In [32]:
from pyspark.sql import functions as F

# 필요한 컬럼 선택
area_2023_2024 = area_df.select('기준_년분기_코드', '상권_코드', '상권_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '당월_매출_금액')

# groupBy와 pivot을 사용해 기준_년분기_코드별 매출 합계 계산
pivot_area = area_2023_2024.groupBy('상권_코드', '상권_코드_명', '서비스_업종_코드', '서비스_업종_코드_명') \
                             .pivot('기준_년분기_코드') \
                             .agg(F.sum('당월_매출_금액'))

# 컬럼명을 기준_년분기_코드 -> '20231_매출 금액', '20232_매출 금액' 형식으로 변경
new_column_names = [f'{int(col)}_매출 금액' if col.isdigit() else col for col in pivot_area.columns]
pivot_area = pivot_area.toDF(*new_column_names)

# 결과 출력
pivot_area.show()

+---------+------------------------+----------------+-------------------+---------------+---------------+---------------+---------------+---------------+
|상권_코드|            상권_코드_명|서비스_업종_코드|서비스_업종_코드_명|20231_매출 금액|20232_매출 금액|20233_매출 금액|20234_매출 금액|20241_매출 금액|
+---------+------------------------+----------------+-------------------+---------------+---------------+---------------+---------------+---------------+
|  3110486|                은평구청|        CS300022|             화장품|       32130689|       29506468|       19825660|           NULL|           NULL|
|  3110610|            계남근린공원|        CS200028|             미용실|       52051061|       46192713|       51980548|       49048799|       59157121|
|  3120232|              송파나루역|        CS100008|         분식전문점|       42000000|       42000000|       36773067|       32400649|       30847924|
|  3120215|            포스코사거리|        CS300024|      운동/경기용품|      378933324|      304237261|      336489700|      383842145|      293545577|
|  3130042|                약수시장|        CS300018|             의약품|      302597439|      356920748|      199322971|      260117211|      243810634|
|  3120169|                  서초역|        CS300028|               화초|       54016240|       83801504|       55104361|      122121202|       57881504|
|  3110465|            연신내역 7번|        CS300018|             의약품|      831547803|      843674420|      806324752|      854433177|      818399463|
|  3110901|인헌고등학교(인헌중학교)|        CS100001|         한식음식점|      298155212|      317745705|      285157890|      284071978|      286639093|
|  3130303|            영동전통시장|        CS100009|      호프-간이주점|     1449237907|     1353724854|     1196621747|     1225239100|     1201668815|
|  3111006|          석촌고분역 1번|        CS200028|             미용실|      450099936|      375846001|      381445906|      353326831|      325334910|
|  3120191|                  학동역|        CS100006|       패스트푸드점|      265594294|      272638100|      272940572|      217217180|      225972068|
|  3110426|         상계2동주민센터|        CS100008|         분식전문점|        2177618|        2360919|        1902143|        2527985|         205298|
|  3120114|            목동신시가지|        CS200008|             한의원|      158903230|      113576748|      150290428|      145978326|      166963879|
|  3110315|         종암아이파크2차|        CS200019|               PC방|      155729902|      112466625|           NULL|           NULL|           NULL|
|  3110593|         신월3동주민센터|        CS300011|           일반의류|       10911754|       10451366|       10905652|       13985816|       10558975|
|  3110262|              상봉역 3번|        CS300001|           슈퍼마켓|      227595173|      223537114|      202406876|      225595735|      227663030|
|  3110668|         화곡2동주민센터|        CS200028|             미용실|       91964071|      106994962|      115649253|      116082282|      133866220|
|  3110781|          대림한신아파트|        CS200031|             세탁소|       35330734|       44749227|       24706144|       38025509|       27363254|
|  3130072|        성동용답상가시장|        CS300017|       시계및귀금속|       73942836|       96260400|      103971282|      107660203|       55856851|
|  3110071|      한강미주맨션아파트|        CS100004|         양식음식점|      574846870|      768283656|      744357354|      742013529|      961539463|
+---------+------------------------+----------------+-------------------+---------------+---------------+---------------+---------------+---------------+
only showing top 20 rows

In [33]:
# 필요한 컬럼 선택
dong_2023_2024 = dong_df.select('기준_년분기_코드', '행정동_코드','행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '당월_매출_금액')

# groupBy와 pivot을 사용해 기준_년분기_코드별 매출 합계 계산
pivot_dong = dong_2023_2024.groupBy('행정동_코드','행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명') \
                             .pivot('기준_년분기_코드') \
                             .agg(F.sum('당월_매출_금액'))

# 컬럼명을 기준_년분기_코드 -> '20231_매출 금액', '20232_매출 금액' 형식으로 변경
new_column_names = [f'{int(col)}_매출 금액' if col.isdigit() else col for col in pivot_dong.columns]
pivot_dong = pivot_dong.toDF(*new_column_names)

# 결과 출력
pivot_dong.show()

+-----------+--------------+----------------+-------------------+---------------+---------------+---------------+---------------+---------------+
|행정동_코드|행정동_코드_명|서비스_업종_코드|서비스_업종_코드_명|20231_매출 금액|20232_매출 금액|20233_매출 금액|20234_매출 금액|20241_매출 금액|
+-----------+--------------+----------------+-------------------+---------------+---------------+---------------+---------------+---------------+
|   11440555|        아현동|        CS300008|         수산물판매|      510887873|      516211553|      435961608|      543852104|      458023542|
|   11320521|       도봉1동|        CS100005|             제과점|      271826450|      274755999|      207153671|      289624023|      266025356|
|   11440600|        대흥동|        CS300007|           육류판매|     1025984864|      834662087|      902717696|      729004327|      858537290|
|   11305535|        미아동|        CS100009|      호프-간이주점|      827427142|      889090484|      954638375|     1022586936|      887682263|
|   11320690|       방학1동|        CS300007|           육류판매|     1080465062|      826717151|      961264135|      825520470|      909924317|
|   11710641|       문정1동|        CS200025|         자동차수리|     1747380025|     1638180779|     1646942801|     1578542167|     1465155549|
|   11740700|       둔촌2동|        CS100002|         중식음식점|      118574754|      116573753|      130411123|      125449233|      105107583|
|   11200670|    성수2가1동|        CS300035|           인테리어|           NULL|       24957588|           NULL|       49915177|           NULL|
|   11500535|       등촌3동|        CS200030|         피부관리실|      427328844|      488424457|      443930051|      427443597|      621375316|
|   11260580|       상봉1동|        CS100001|         한식음식점|     1190275439|     1382532922|     1370135870|     1168193458|     1104522012|
|   11350700|       상계8동|        CS200001|       일반교습학원|      845783394|      877034016|      943572449|      929919560|     1044723124|
|   11440610|        염리동|        CS300028|               화초|       49979508|       43398527|       29127177|       30215755|       29992076|
|   11290685|       길음2동|        CS100010|          커피-음료|      928612033|      992936025|      965485356|      865502729|      838416246|
|   11470540|         목4동|        CS200024|         스포츠클럽|       67593481|        5499509|       67723508|       78735273|       49870052|
|   11590550|       상도3동|        CS100007|         치킨전문점|      272041702|      402499981|      350422340|      328364865|      235276975|
|   11710600|        석촌동|        CS200024|         스포츠클럽|     2460565700|     1466577427|     1204423831|     1323855911|     1570603914|
|   11290575|        동선동|        CS300004|             핸드폰|       21649305|       25162796|       10473304|       15190682|       45158694|
|   11350720|      상계10동|        CS200029|             네일숍|       35821552|       34535776|       42242242|       50161639|       49662069|
|   11230570|       전농2동|        CS300028|               화초|       35878293|       54307232|       13142174|       29704837|       39622813|
|   11500591|       화곡6동|        CS300018|             의약품|     1519589993|     1511109653|     1526483715|     1482616619|     1439994578|
+-----------+--------------+----------------+-------------------+---------------+---------------+---------------+---------------+---------------+
only showing top 20 rows

In [34]:
# 필요한 컬럼 선택
gu_2023_2024 = gu_df.select('기준_년분기_코드', '자치구_코드','자치구_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '당월_매출_금액')

# groupBy와 pivot을 사용해 기준_년분기_코드별 매출 합계 계산
pivot_gu = gu_2023_2024.groupBy('자치구_코드','자치구_코드_명', '서비스_업종_코드', '서비스_업종_코드_명') \
                             .pivot('기준_년분기_코드') \
                             .agg(F.sum('당월_매출_금액'))

# 컬럼명을 기준_년분기_코드 -> '20231_매출 금액', '20232_매출 금액' 형식으로 변경
new_column_names = [f'{int(col)}_매출 금액' if col.isdigit() else col for col in pivot_gu.columns]
pivot_gu = pivot_gu.toDF(*new_column_names)

# 결과 출력
pivot_gu.show()

+-----------+--------------+----------------+----------------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+
|자치구_코드|자치구_코드_명|서비스_업종_코드|   서비스_업종_코드_명|20191_매출 금액|20192_매출 금액|20193_매출 금액|20194_매출 금액|20201_매출 금액|20202_매출 금액|20203_매출 금액|20204_매출 금액|20211_매출 금액|20212_매출 금액|20213_매출 금액|20214_매출 금액|20221_매출 금액|20222_매출 금액|20223_매출 금액|20224_매출 금액|20231_매출 금액|20232_매출 금액|20233_매출 금액|20234_매출 금액|20241_매출 금액|
+-----------+--------------+----------------+----------------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+
|      11140|          중구|        CS300031|                  가구|    23645491456|    32362215072|    33165983813|    38677407312|    19415342090|    31977813663|    28114201914|    25475280825|    21940017629|    29184152156|    21414051807|    29341181787|    19965539699|    23505569485|    24534982051|    25179658911|    21111112110|    29487391674|    29320813861|    23544390091|    19720671807|
|      11590|        동작구|        CS200007|              치과의원|    25930383390|    26004758954|    24938588060|    27836507484|    25832728630|    26343651754|    27712006106|    26406458035|    26702522401|    27050229133|    28081544087|    27715858550|    26465518041|    26573060154|    26845261916|    27360453267|    27441425365|    27170940942|    26910051371|    26817221453|    26720904805|
|      11215|        광진구|        CS100007|            치킨전문점|     2941007784|     3479970891|     3415683423|     3694936081|     3168471829|     3474805879|     3036854192|     2598984771|     2181743180|     2744089079|     2869657109|     3056032092|     2729362888|     4080969471|     3756286483|     4052121670|     3794292259|     4468314532|     4163218191|     3855165826|     3061673337|
|      11680|        강남구|        CS200016|                당구장|     1483255212|     1395361512|     1518215843|     1543615405|     1827122828|     1655872910|     1418757164|     1128478826|     1202112513|     1639498005|     1721025142|     2093856627|     1965358070|     2922158698|     3342219834|     3356036344|     3579641415|     3289807514|     3775719198|     3949579275|     3870830280|
|      11710|        송파구|        CS300010|              반찬가게|   209293687899|   215012448521|   225935808507|   255791581311|   191305340185|   205243024299|   204495833009|   200999591506|   196096450905|   229808154579|   217821656164|   244980073508|   210394865517|   255447477098|   262586476911|   312624513914|   286796051507|   267492179673|   256598799998|   279915559856|   231991783660|
|      11215|        광진구|        CS300033|                철물점|     4158760729|     3303018720|     3994947665|     8148624978|     4465976806|     4449872477|     6415477900|     8947849037|     8978615960|     4320080176|     4369617546|     9230627133|     6404667394|     3809276550|     4153674698|     9539510265|     7081060670|     4015012385|     4189556586|     9789346194|     9098581583|
|      11215|        광진구|        CS300019|              의료기기|     2683225446|     2441414633|     5135407321|     6853049791|     8800880056|     8906950103|     8332843844|     6189062763|     4744166761|    12080833226|     7099275478|     9236028434|     7975433227|     8883023241|    12599311995|    10604516518|    11664326478|    11483501461|    11072581898|    11554836583|    12266990817|
|      11380|        은평구|        CS100004|            양식음식점|     1312136130|     1376192319|     1492669528|     1433526226|     1142679864|     1270324544|     1351041300|     1239163873|     1176516656|     1614250904|     1925367425|     2304968677|     1985393747|     2692633648|     2606767623|     2669970079|     2838780386|     3162183587|     3032236806|     2934402416|     2638516971|
|      11260|        중랑구|        CS300006|              미곡판매|     1773589368|     1721565431|     1583497556|     4509968171|     4228954855|     3551953725|     3479415320|     3262751797|     2963131573|     2727474549|     3516663026|     3732944994|     3242772772|     3672860542|     3338319370|     3666578395|     2794848118|     3343737544|     3485636268|     4670406014|     6616473613|
|      11740|        강동구|        CS300024|         운동/경기용품|     5711538619|     7990827735|     6436826420|     6183101652|     5983197655|     7902671799|    10916998864|     9677694594|     9610728218|    10668955284|    10892705211|     8581014893|     7536769275|    12559612175|     9301732937|     9943371587|     7070453616|    10598725825|     7774852156|     5157517493|     8448396142|
|      11110|        종로구|        CS200030|            피부관리실|      468109314|      390122790|      501504461|      400941475|      321695757|      389057424|      438839098|      366325598|      449908109|      464643434|      460215515|      515602983|      305466102|      565689406|      648916646|      606599448|      561781618|      569346323|      708118917|      579145509|      578426578|
|      11470|        양천구|        CS100006|          패스트푸드점|     4794331791|     4659752086|     4708493467|     4504028099|     4152866527|     4331305910|     4331090770|     4275613264|     4171991226|     3972878933|     4593877669|     4878807408|     5089033828|     5422839336|     5692319009|     5310384156|     5394236808|     5804287178|     5947934656|     5307765716|     5068555955|
|      11290|        성북구|        CS200016|                당구장|      474310064|      563627664|      577084068|      618596396|      654175992|      703221611|      629690064|      436444820|      454032244|      524075000|      827200281|      821157204|      702627558|      924601786|      947816931|      864957370|     1017256076|     1126998035|     1211517689|     1032365986|     1215865495|
|      11440|        마포구|        CS200030|            피부관리실|     2108992593|     2306631203|     2419152604|     2569657113|     2281773550|     2656498980|     2537778487|     2301060333|     2270601464|     2737523679|     2535643402|     3042149967|     2565970298|     2913081875|     3313823498|     3125835110|     3013335958|     3418055864|     3458521159|     2697011636|     3272073223|
|      11620|        관악구|        CS300025|자전거 및 기타운송장비|      204107903|      554637460|      597632595|      559560649|      495731739|      775724604|      731734612|      540737330|      541137890|      782529042|     1205858868|      502371138|      306769364|      952752332|      937867080|      592867799|      758428326|     1125663379|      689377619|      725821878|      234557121|
|      11320|        도봉구|        CS100005|                제과점|     3480039948|     4041305802|     4038423967|     3394681838|     3310716890|     3715835753|     3747088675|     3303912021|     3502229523|     4046682358|     4734109650|     4642633271|     4535370619|     5568450687|     6968630144|     6784631008|     6664134537|     7133714528|     7412120430|     6945694437|     6932318371|
|      11170|        용산구|        CS100008|            분식전문점|     7139346473|     8429819997|     8038033834|     9124830779|     7077888317|     7324688306|     7397014907|     7477240119|     6487919137|     7964101538|     6908643194|     8287855427|     7208039571|    10189717948|    10747067965|    11081530015|    10689209476|    11615355297|    11008859913|    11103181650|     9854591130|
|      11710|        송파구|        CS200028|                미용실|    11844384907|    12431298920|    12930986122|    12686748434|    11793227386|    13419898553|    13213777436|    12651375800|    13492367027|    14662740853|    16790968013|    17042231222|    16177378401|    18121475782|    19901973233|    19779556190|    19423510637|    20605760137|    20675249864|    20928527782|    19264833226|
|      11650|        서초구|        CS300033|                철물점|     1271577863|     1414298001|     1654551531|     1584224284|     1286088835|     1621615512|     2111972605|     1940870487|     2138239400|     2315055266|     2276210249|     2592144753|     2292724939|     2437480039|     2812488817|     2419347756|     2064215922|     2552841115|     2448172352|     2894279522|     2534417530|
|      11350|        노원구|        CS200006|              일반의원|    44851144118|    48569878959|    47473330620|    54370882565|    49002989584|    47498016015|    51355395993|    51498236536|    51171982850|    56791455295|    55169053817|    63480086851|    62191665855|    63681837564|    61853943652|    67042149647|    67342173632|    71009937917|    71365801350|    78763740874|    73069326512|
+-----------+--------------+----------------+----------------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+
only showing top 20 rows

In [35]:
pivot_gu = pivot_gu.select('자치구_코드','자치구_코드_명','서비스_업종_코드','서비스_업종_코드_명','20231_매출 금액','20232_매출 금액','20233_매출 금액','20234_매출 금액','20241_매출 금액')
pivot_gu.show()

+-----------+--------------+----------------+----------------------+---------------+---------------+---------------+---------------+---------------+
|자치구_코드|자치구_코드_명|서비스_업종_코드|   서비스_업종_코드_명|20231_매출 금액|20232_매출 금액|20233_매출 금액|20234_매출 금액|20241_매출 금액|
+-----------+--------------+----------------+----------------------+---------------+---------------+---------------+---------------+---------------+
|      11140|          중구|        CS300031|                  가구|    21111112110|    29487391674|    29320813861|    23544390091|    19720671807|
|      11590|        동작구|        CS200007|              치과의원|    27441425365|    27170940942|    26910051371|    26817221453|    26720904805|
|      11215|        광진구|        CS100007|            치킨전문점|     3794292259|     4468314532|     4163218191|     3855165826|     3061673337|
|      11680|        강남구|        CS200016|                당구장|     3579641415|     3289807514|     3775719198|     3949579275|     3870830280|
|      11710|        송파구|        CS300010|              반찬가게|   286796051507|   267492179673|   256598799998|   279915559856|   231991783660|
|      11215|        광진구|        CS300033|                철물점|     7081060670|     4015012385|     4189556586|     9789346194|     9098581583|
|      11215|        광진구|        CS300019|              의료기기|    11664326478|    11483501461|    11072581898|    11554836583|    12266990817|
|      11380|        은평구|        CS100004|            양식음식점|     2838780386|     3162183587|     3032236806|     2934402416|     2638516971|
|      11260|        중랑구|        CS300006|              미곡판매|     2794848118|     3343737544|     3485636268|     4670406014|     6616473613|
|      11740|        강동구|        CS300024|         운동/경기용품|     7070453616|    10598725825|     7774852156|     5157517493|     8448396142|
|      11110|        종로구|        CS200030|            피부관리실|      561781618|      569346323|      708118917|      579145509|      578426578|
|      11470|        양천구|        CS100006|          패스트푸드점|     5394236808|     5804287178|     5947934656|     5307765716|     5068555955|
|      11290|        성북구|        CS200016|                당구장|     1017256076|     1126998035|     1211517689|     1032365986|     1215865495|
|      11440|        마포구|        CS200030|            피부관리실|     3013335958|     3418055864|     3458521159|     2697011636|     3272073223|
|      11620|        관악구|        CS300025|자전거 및 기타운송장비|      758428326|     1125663379|      689377619|      725821878|      234557121|
|      11320|        도봉구|        CS100005|                제과점|     6664134537|     7133714528|     7412120430|     6945694437|     6932318371|
|      11170|        용산구|        CS100008|            분식전문점|    10689209476|    11615355297|    11008859913|    11103181650|     9854591130|
|      11710|        송파구|        CS200028|                미용실|    19423510637|    20605760137|    20675249864|    20928527782|    19264833226|
|      11650|        서초구|        CS300033|                철물점|     2064215922|     2552841115|     2448172352|     2894279522|     2534417530|
|      11350|        노원구|        CS200006|              일반의원|    67342173632|    71009937917|    71365801350|    78763740874|    73069326512|
+-----------+--------------+----------------+----------------------+---------------+---------------+---------------+---------------+---------------+
only showing top 20 rows

In [36]:
# area_2024, dong_2024, gu_2024, pivot_gu,pivot_area, pivot_dong넣으면 됨

In [37]:
def sh_area(row):
          # 삽입할 SQL 쿼리 정의
            sql = """
            INSERT INTO sales_history (service_code, area_id, dong_code, gu_code, sales_20231, sales_20232, sales_20233, sales_20234, sales_20241)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            # 데이터 삽입
            cursor.execute(sql, (
                row['서비스_업종_코드'],  # service_code
                row['상권_코드'],        # area_id
                None,                   # dong_code (NULL 값)
                None,                   # gu_code (NULL 값)
                row['20231_매출 금액'],   # sales_20231
                row['20232_매출 금액'],   # sales_20232
                row['20233_매출 금액'],   # sales_20233
                row['20234_매출 금액'],   # sales_20234
                row['20241_매출 금액']    # sales_20241
            ))

In [38]:
def sh_dong(row):
          # 삽입할 SQL 쿼리 정의
            sql = """
            INSERT INTO sales_history (service_code, area_id, dong_code, gu_code, sales_20231, sales_20232, sales_20233, sales_20234, sales_20241)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            # 데이터 삽입
            cursor.execute(sql, (
                row['서비스_업종_코드'],  # service_code
                None,        # area_id
                row['행정동_코드'],                   # dong_code (NULL 값)
                None,                   # gu_code (NULL 값)
                row['20231_매출 금액'],   # sales_20231
                row['20232_매출 금액'],   # sales_20232
                row['20233_매출 금액'],   # sales_20233
                row['20234_매출 금액'],   # sales_20234
                row['20241_매출 금액']    # sales_20241
            ))

In [39]:
def sh_gu(row):
          # 삽입할 SQL 쿼리 정의
            sql = """
            INSERT INTO sales_history (service_code, area_id, dong_code, gu_code, sales_20231, sales_20232, sales_20233, sales_20234, sales_20241)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            # 데이터 삽입
            cursor.execute(sql, (
                row['서비스_업종_코드'],  # service_code
                None,        # area_id
                None,                   # dong_code (NULL 값)
                row['자치구_코드'],                   # gu_code (NULL 값)
                row['20231_매출 금액'],   # sales_20231
                row['20232_매출 금액'],   # sales_20232
                row['20233_매출 금액'],   # sales_20233
                row['20234_매출 금액'],   # sales_20234
                row['20241_매출 금액']    # sales_20241
            ))

In [40]:
def s_gu(row):
          # 삽입할 SQL 쿼리 정의
            sql = """
            INSERT INTO sales (year, gu_code, service_code, month_sales, week_sales, weekend_sales,
                                       mon_sales, tue_sales, wed_sales, thu_sales, fri_sales, sat_sales, sun_sales,
                                       0to6, 6to11, 11to14, 14to17, 17to21, 21to24, man_sales, woman_sales,
                                       10_sales, 20_sales, 30_sales, 40_sales, 50_sales, 60_sales)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            # MariaDB에 데이터를 삽입할 때, 필요한 컬럼을 맞추어 삽입
            cursor.execute(sql, (
                row['기준_년분기_코드'],  # year
                row['자치구_코드'],         # area_id
                row['서비스_업종_코드'],   # service_code
                row['당월_매출_금액'],     # month_sales
                row['주중_매출_금액'],     # week_sales
                row['주말_매출_금액'],     # weekend_sales
                row['월요일_매출_금액'],   # mon_sales
                row['화요일_매출_금액'],   # tue_sales
                row['수요일_매출_금액'],   # wed_sales
                row['목요일_매출_금액'],   # thu_sales
                row['금요일_매출_금액'],   # fri_sales
                row['토요일_매출_금액'],   # sat_sales
                row['일요일_매출_금액'],   # sun_sales
                row['시간대_00~06_매출_금액'],  # 0to6
                row['시간대_06~11_매출_금액'],  # 6to11
                row['시간대_11~14_매출_금액'],  # 11to14
                row['시간대_14~17_매출_금액'],  # 14to17
                row['시간대_17~21_매출_금액'],  # 17to21
                row['시간대_21~24_매출_금액'],  # 21to24
                row['남성_매출_금액'],     # man_sales
                row['여성_매출_금액'],     # woman_sales
                row['연령대_10_매출_금액'],  # 10_sales
                row['연령대_20_매출_금액'],  # 20_sales
                row['연령대_30_매출_금액'],  # 30_sales
                row['연령대_40_매출_금액'],  # 40_sales
                row['연령대_50_매출_금액'],  # 50_sales
                row['연령대_60_이상_매출_금액']  # 60_sales
            ))

In [41]:
def s_dong(row):
          # 삽입할 SQL 쿼리 정의
            sql = """
            INSERT INTO sales (year, dong_code, service_code, month_sales, week_sales, weekend_sales,
                                       mon_sales, tue_sales, wed_sales, thu_sales, fri_sales, sat_sales, sun_sales,
                                       0to6, 6to11, 11to14, 14to17, 17to21, 21to24, man_sales, woman_sales,
                                       10_sales, 20_sales, 30_sales, 40_sales, 50_sales, 60_sales)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            # MariaDB에 데이터를 삽입할 때, 필요한 컬럼을 맞추어 삽입
            cursor.execute(sql, (
                row['기준_년분기_코드'],  # year
                row['행정동_코드'],         # area_id
                row['서비스_업종_코드'],   # service_code
                row['당월_매출_금액'],     # month_sales
                row['주중_매출_금액'],     # week_sales
                row['주말_매출_금액'],     # weekend_sales
                row['월요일_매출_금액'],   # mon_sales
                row['화요일_매출_금액'],   # tue_sales
                row['수요일_매출_금액'],   # wed_sales
                row['목요일_매출_금액'],   # thu_sales
                row['금요일_매출_금액'],   # fri_sales
                row['토요일_매출_금액'],   # sat_sales
                row['일요일_매출_금액'],   # sun_sales
                row['시간대_00~06_매출_금액'],  # 0to6
                row['시간대_06~11_매출_금액'],  # 6to11
                row['시간대_11~14_매출_금액'],  # 11to14
                row['시간대_14~17_매출_금액'],  # 14to17
                row['시간대_17~21_매출_금액'],  # 17to21
                row['시간대_21~24_매출_금액'],  # 21to24
                row['남성_매출_금액'],     # man_sales
                row['여성_매출_금액'],     # woman_sales
                row['연령대_10_매출_금액'],  # 10_sales
                row['연령대_20_매출_금액'],  # 20_sales
                row['연령대_30_매출_금액'],  # 30_sales
                row['연령대_40_매출_금액'],  # 40_sales
                row['연령대_50_매출_금액'],  # 50_sales
                row['연령대_60_이상_매출_금액']  # 60_sales
            ))

In [42]:
def s_area(row):
          # 삽입할 SQL 쿼리 정의
            sql = """
            INSERT INTO sales (year, area_id, service_code, month_sales, week_sales, weekend_sales,
                                       mon_sales, tue_sales, wed_sales, thu_sales, fri_sales, sat_sales, sun_sales,
                                       0to6, 6to11, 11to14, 14to17, 17to21, 21to24, man_sales, woman_sales,
                                       10_sales, 20_sales, 30_sales, 40_sales, 50_sales, 60_sales)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            # MariaDB에 데이터를 삽입할 때, 필요한 컬럼을 맞추어 삽입
            cursor.execute(sql, (
                row['기준_년분기_코드'],  # year
                row['상권_코드'],         # area_id
                row['서비스_업종_코드'],   # service_code
                row['당월_매출_금액'],     # month_sales
                row['주중_매출_금액'],     # week_sales
                row['주말_매출_금액'],     # weekend_sales
                row['월요일_매출_금액'],   # mon_sales
                row['화요일_매출_금액'],   # tue_sales
                row['수요일_매출_금액'],   # wed_sales
                row['목요일_매출_금액'],   # thu_sales
                row['금요일_매출_금액'],   # fri_sales
                row['토요일_매출_금액'],   # sat_sales
                row['일요일_매출_금액'],   # sun_sales
                row['시간대_00~06_매출_금액'],  # 0to6
                row['시간대_06~11_매출_금액'],  # 6to11
                row['시간대_11~14_매출_금액'],  # 11to14
                row['시간대_14~17_매출_금액'],  # 14to17
                row['시간대_17~21_매출_금액'],  # 17to21
                row['시간대_21~24_매출_금액'],  # 21to24
                row['남성_매출_금액'],     # man_sales
                row['여성_매출_금액'],     # woman_sales
                row['연령대_10_매출_금액'],  # 10_sales
                row['연령대_20_매출_금액'],  # 20_sales
                row['연령대_30_매출_금액'],  # 30_sales
                row['연령대_40_매출_금액'],  # 40_sales
                row['연령대_50_매출_금액'],  # 50_sales
                row['연령대_60_이상_매출_금액']  # 60_sales
            ))

In [43]:
cursor = connection.cursor()

# DataFrame의 각 행을 MariaDB에 삽입
for row in pivot_gu.collect():
    sh_gu(row)

# DataFrame의 각 행을 MariaDB에 삽입
for row in pivot_dong.collect():
    sh_dong(row)

# DataFrame의 각 행을 MariaDB에 삽입
for row in pivot_area.collect():
    sh_area(row)

# DataFrame의 각 행을 MariaDB에 삽입
for row in gu_2024.collect():
    s_gu(row)

# DataFrame의 각 행을 MariaDB에 삽입
for row in dong_2024.collect():
    s_dong(row)

# DataFrame의 각 행을 MariaDB에 삽입
for row in area_2024.collect():
    s_area(row)

# 변경사항 커밋 및 연결 종료
connection.commit()
cursor.close()
connection.close()

IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`S11P21D108`.`sales_history`, CONSTRAINT `FK_dong_TO_sales_history_1` FOREIGN KEY (`dong_code`) REFERENCES `dong` (`id`))